### ISSUE TITLE
Site is down!

### ISSUE THREAD

**Issue by ryan-williams** [iest/i-am-the-fold#27]
Seems to be down again! https://iamthefold.com/

![image](https://github.com/iest/i-am-the-fold/assets/465045/6de2d107-4770-488a-a558-cff36d179722)

xref #8

**Comment by iest** [comment]
Sorry, totally missed this issue somehow as my notifications were messed up.

Thanks for letting me know! I'm working on a fix and general cleanup now 👍

**Comment by iest** [comment]
Closed by #28
